#!/bin/bash

EXPERIMENT_DIR=spearmint-config/gp-test
GP_INDICES="100 5 90 71 2 999 33 400 500"
STEP=20
source python2-env/bin/activate

for i in ${GP_INDICES[@]}
do
    echo "---------- GP-Test $i -----------"
    mongo spearmint --eval 'db.gp_test.hypers.drop(); db.gp_test.jobs.drop(); db.dropDatabase()' && \
        rm -rf $EXPERIMENT_DIR/output/* && \
        GP_TEST_INDEX=$i python bayesian-optimization/Spearmint/spearmint/main.py $EXPERIMENT_DIR --steps $STEP && \
        cat $EXPERIMENT_DIR/output/* | grep 'job #' > $EXPERIMENT_DIR/runs/"gp-$i"
done

