#!/bin/bash

EXPERIMENT_DIR=spearmint-config/gp-test-ith
GP_TEST_INDEX=$1
TOTAL_RUNS=100
STEP=20

source python2-env/bin/activate


RUN_DIR=$EXPERIMENT_DIR/runs-$GP_TEST_INDEX-th
mkdir $RUN_DIR

rm -rf $RUN_DIR/*

for i in `seq 1 $TOTAL_RUNS`
do
    echo "---------- RUN $i -----------"
    mongo spearmint --eval 'db.gp_test_ith.hypers.drop(); db.gp_test_ith.jobs.drop(); db.dropDatabase()' && \
        rm -rf $EXPERIMENT_DIR/output/* && \
        GP_TEST_INDEX=$GP_TEST_INDEX python bayesian-optimization/Spearmint/spearmint/main.py $EXPERIMENT_DIR --steps $STEP && \
        cat $EXPERIMENT_DIR/output/* | grep 'job #' > $RUN_DIR/`date +%s`
done

